version: '3.9'

services:
  task-scheduler:
    image: 'task-scheduler:latest'
    build:
      context: .
    container_name: task-scheduler
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - job1.enabled=false
      - job2.enabled=true
      - job2.random-lock.enabled=false
      - lock-provider.keep-alive.enabled=true
      - lockAtMostFor=30
      - jobs.delay=60

  task-scheduler-2:
    image: 'task-scheduler:latest'
    build:
      context: .
    container_name: task-scheduler-2
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
